In [1]:
#!/usr/local/bin/python3.6

import numpy as np
import matplotlib.pyplot as plt
plt.rcParams['figure.figsize'] = (7,7) # Make the figures a bit bigger , size of the figure

from keras.datasets import mnist
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation
from keras.utils import np_utils


nb_classes = 10

# the data, shuffled and split between tran and test sets
(X_train, y_train), (X_test, y_test) = mnist.load_data()

#print("X_train original shape", X_train.shape)
#print("y_train original shape", y_train.shape)


for i in range(9):
    plt.subplot(3,3,i+1)
    plt.imshow(X_train[i], cmap='gray', interpolation='none')
    plt.title("Class {}".format(y_train[i]))
    #plt.show()
    



X_train = X_train.reshape(60000, 784)
X_test = X_test.reshape(10000, 784)
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255
X_test /= 255
#print("Training matrix shape", X_train.shape)
#print(X_train)
#print("Testing matrix shape", X_test.shape)


Y_train = np_utils.to_categorical(y_train, nb_classes)
Y_test = np_utils.to_categorical(y_test, nb_classes)

# change une matrice de [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] en 5

'''
model = Sequential()
model.add(Dense(512, input_shape=(784,)))
model.add(Activation('relu')) # An "activation" is just a non-linear function applied to the output
                              # of the layer above. Here, with a "rectified linear unit",
                              # we clamp all values below 0 to 0.
                           
model.add(Dropout(0.2))   # Dropout helps protect the model from memorizing or "overfitting" the training data
model.add(Dense(512))
model.add(Activation('relu'))
model.add(Dropout(0.2))
model.add(Dense(10))
model.add(Activation('softmax')) # This special "softmax" activation among other things,
                                 # ensures the output is a valid probaility distribution, that is
                                 # that its values are all non-negative and sum to 1.
                
# compilation du model ###############################################

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# training  ###########################################################

model.fit(X_train, Y_train, batch_size=128, nb_epoch=4, verbose=1,
         validation_data=(X_test, Y_test))
         
# evualtion ###########################################################
         
score = model.evaluate(X_test, Y_test, verbose=0)
print('Test score:', score[0])
print('Test accuracy:', score[1])

#######################################################################

# The predict_classes function outputs the highest probability class
# according to the trained classifier for each input example.
predicted_classes = model.predict_classes(X_test)

# Check which items we got right / wrong
correct_indices = np.nonzero(predicted_classes == y_test)[0]
incorrect_indices = np.nonzero(predicted_classes != y_test)[0]
'''

Using TensorFlow backend.


Training matrix shape (60000, 784)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


'\nmodel = Sequential()\nmodel.add(Dense(512, input_shape=(784,)))\nmodel.add(Activation(\'relu\')) # An "activation" is just a non-linear function applied to the output\n                              # of the layer above. Here, with a "rectified linear unit",\n                              # we clamp all values below 0 to 0.\n                           \nmodel.add(Dropout(0.2))   # Dropout helps protect the model from memorizing or "overfitting" the training data\nmodel.add(Dense(512))\nmodel.add(Activation(\'relu\'))\nmodel.add(Dropout(0.2))\nmodel.add(Dense(10))\nmodel.add(Activation(\'softmax\')) # This special "softmax" activation among other things,\n                                 # ensures the output is a valid probaility distribution, that is\n                                 # that its values are all non-negative and sum to 1.\n                \n# compilation du model ###############################################\n\nmodel.compile(loss=\'categorical_crossentropy\', optimize

In [ ]:
plt.figure()
for i, correct in enumerate(correct_indices[:9]):
    plt.subplot(3,3,i+1)
    plt.imshow(X_test[correct].reshape(28,28), cmap='gray', interpolation='none')
    plt.title("Predicted {}, Class {}".format(predicted_classes[correct], y_test[correct]))
    plt.show()
    
plt.figure()
for i, incorrect in enumerate(incorrect_indices[:9]):
    plt.subplot(3,3,i+1)
    plt.imshow(X_test[incorrect].reshape(28,28), cmap='gray', interpolation='none')
    plt.title("Predicted {}, Class {}".format(predicted_classes[incorrect], y_test[incorrect]))
    plt.show()
